#Word Embedding

In [14]:
import numpy as np

#Quote by Richard Feynman

In [6]:
Quote=['We are at the very beginning of time for the human race',
        'It is not unreasonable that we grapple with problems', 
        'But there are tens of thousands of years in the future', 
        'Our responsibility is to do what we can, learn what we can', 
        'improve the solutions, and pass them on',
        'Richard P. Feynman']
Quote

['We are at the very beginning of time for the human race',
 'It is not unreasonable that we grapple with problems',
 'But there are tens of thousands of years in the future',
 'Our responsibility is to do what we can, learn what we can',
 'improve the solutions, and pass them on',
 'Richard P. Feynman']

#Choose vocab size

In [7]:
### Vocabulary size
voc_size=10000

#One hot encoding all words

In [10]:
from tensorflow.keras.preprocessing.text import one_hot
onehot_repr=[one_hot(words,voc_size)for words in Quote] 
print(onehot_repr)

[[9960, 686, 274, 5257, 198, 3542, 3772, 1244, 2954, 5257, 6450, 1042], [1533, 7061, 8852, 3369, 902, 9960, 2399, 6414, 5195], [5562, 7491, 686, 5103, 3772, 2397, 3772, 2534, 2310, 5257, 1325], [784, 9990, 7061, 6465, 495, 4668, 9960, 504, 1244, 4668, 9960, 504], [7956, 5257, 9641, 9352, 9621, 2445, 7045], [6134, 4528, 1790]]


#Pre padding sentences

In [13]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
sent_length=14
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0 9960  686  274 5257  198 3542 3772 1244 2954 5257 6450 1042]
 [   0    0    0    0    0 1533 7061 8852 3369  902 9960 2399 6414 5195]
 [   0    0    0 5562 7491  686 5103 3772 2397 3772 2534 2310 5257 1325]
 [   0    0  784 9990 7061 6465  495 4668 9960  504 1244 4668 9960  504]
 [   0    0    0    0    0    0    0 7956 5257 9641 9352 9621 2445 7045]
 [   0    0    0    0    0    0    0    0    0    0    0 6134 4528 1790]]


#Word Embedding

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
dim=10 #NO of Features
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 14, 10)            100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(model.predict(embedded_docs))

[[[-7.07052648e-04 -4.97542620e-02 -2.97119617e-02  4.91413958e-02
   -4.60205674e-02  4.33125384e-02 -2.66009569e-03  3.85595225e-02
   -1.10496208e-03 -2.91192178e-02]
  [-7.07052648e-04 -4.97542620e-02 -2.97119617e-02  4.91413958e-02
   -4.60205674e-02  4.33125384e-02 -2.66009569e-03  3.85595225e-02
   -1.10496208e-03 -2.91192178e-02]
  [-4.62982804e-03  3.33916396e-04  1.79879181e-02 -2.79763825e-02
   -3.30619887e-03  1.95545442e-02  1.96718015e-02 -2.61284839e-02
   -4.47011851e-02  3.34899500e-03]
  [-3.43453437e-02  9.74954292e-03  5.32351807e-03 -2.51913797e-02
    1.44637860e-02  1.14803538e-02 -3.95162813e-02 -1.33392103e-02
   -3.72736454e-02 -2.26478111e-02]
  [-3.88239399e-02 -1.12187378e-02 -3.78893018e-02 -4.99983095e-02
   -1.90005898e-02 -1.85335502e-02 -3.01404949e-02 -4.46804166e-02
   -4.22281027e-03 -1.54937133e-02]
  [-9.67007875e-03  2.07905844e-03 -4.68151346e-02  2.85258330e-02
   -4.79977839e-02  3.52768041e-02 -8.78623873e-03 -1.53161995e-02
    2.93711685e-

In [20]:
embedded_docs[0]

array([   0,    0, 9960,  686,  274, 5257,  198, 3542, 3772, 1244, 2954,
       5257, 6450, 1042], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0])

[[-0.00070705 -0.04975426 -0.02971196  0.0491414  -0.04602057  0.04331254
  -0.0026601   0.03855952 -0.00110496 -0.02911922]
 [-0.00070705 -0.04975426 -0.02971196  0.0491414  -0.04602057  0.04331254
  -0.0026601   0.03855952 -0.00110496 -0.02911922]
 [-0.00462983  0.00033392  0.01798792 -0.02797638 -0.0033062   0.01955454
   0.0196718  -0.02612848 -0.04470119  0.003349  ]
 [-0.03434534  0.00974954  0.00532352 -0.02519138  0.01446379  0.01148035
  -0.03951628 -0.01333921 -0.03727365 -0.02264781]
 [-0.03882394 -0.01121874 -0.0378893  -0.04999831 -0.01900059 -0.01853355
  -0.03014049 -0.04468042 -0.00422281 -0.01549371]
 [-0.00967008  0.00207906 -0.04681513  0.02852583 -0.04799778  0.0352768
  -0.00878624 -0.0153162   0.02937117  0.04068765]
 [ 0.00504545  0.04217731 -0.0179569   0.03666059  0.03468964  0.00569648
  -0.01152845  0.01967943  0.04464364 -0.03682842]
 [-0.01904479 -0.04509169  0.02606148 -0.01692206 -0.01903548  0.04529591
   0.0428826  -0.01014141  0.03208088  0.02962155]
 